# Generated by Django 3.1.5 on 2021-01-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serving_count', models.IntegerField(default=1)),
                ('veg_indicator', models.BooleanField(default=True, verbose_name='veg indicator')),
                ('ingredients', models.JSONField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='last modified at')),
            ],
        ),
    ]
